"use client";

import { motion } from "framer-motion";
import { Star } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";

const testimonials = [
  {
    quote:
      "We launched our landing page 3x faster than usual. The AI nailed our brand voice on the first try — I barely had to edit anything.",
    author: "Sarah Chen",
    role: "Co-founder at Depot",
    avatar: "SC",
    color: "bg-violet-500",
  },
  {
    quote:
      "I was skeptical about AI copywriting, but NeuralCopy's output is genuinely good. It actually understands benefit-driven copy, not just features.",
    author: "Marcus Webb",
    role: "Head of Growth at Pylon",
    avatar: "MW",
    color: "bg-blue-500",
  },
  {
    quote:
      "Our conversion rate went up 34% after switching to copy generated by NeuralCopy. The CTA suggestions alone were worth the subscription.",
    author: "Priya Nair",
    role: "Product Designer at Glide",
    avatar: "PN",
    color: "bg-fuchsia-500",
  },
];

export default function Testimonials() {
  return (
    <section className="py-24 bg-card/30 border-y border-border">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <span className="inline-block text-xs font-semibold uppercase tracking-widest text-primary mb-4 border border-primary/30 bg-primary/10 rounded-full px-3 py-1">
            Testimonials
          </span>
          <h2 className="text-4xl md:text-5xl font-bold mb-4">
            Loved by <span className="gradient-text">builders</span>
          </h2>
          <p className="text-muted-foreground text-lg">
            Join 2,000+ founders and marketers already using NeuralCopy.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {testimonials.map((t, i) => (
            <motion.div
              key={t.author}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.12 }}
            >
              <Card className="h-full border-border bg-card hover:border-primary/30 transition-colors">
                <CardContent className="p-6 flex flex-col h-full">
                  <div className="flex gap-1 mb-4">
                    {Array.from({ length: 5 }).map((_, j) => (
                      <Star key={j} className="w-4 h-4 fill-primary text-primary" />
                    ))}
                  </div>
                  <p className="text-foreground/90 leading-relaxed flex-1 mb-6">&quot;{t.quote}&quot;</p>
                  <div className="flex items-center gap-3">
                    <div
                      className={`w-10 h-10 rounded-full ${t.color} flex items-center justify-center text-white text-sm font-bold flex-shrink-0`}
                    >
                      {t.avatar}
                    </div>
                    <div>
                      <p className="font-semibold text-sm">{t.author}</p>
                      <p className="text-muted-foreground text-xs">{t.role}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
